### ISSUE TITLE
Lack of ducks with hats :(

### ISSUE THREAD

**Issue by MaloTV** [ducki-es/ducki-es.github.io#1]
![Image07](https://github.com/ducki-es/ducki-es.github.io/assets/70515562/cc1c4f64-cf35-4ec6-a56a-7fdb204f5f46)
![Image08](https://github.com/ducki-es/ducki-es.github.io/assets/70515562/2cc690c0-f831-4068-ba6d-8ce16890bdb4)
![Image09](https://github.com/ducki-es/ducki-es.github.io/assets/70515562/9f513d1b-b98c-41cf-8705-56e4af63e2a4)
![Image10](https://github.com/ducki-es/ducki-es.github.io/assets/70515562/3202ea9d-3e93-4aad-95c3-4004cd264a40)
![Image11](https://github.com/ducki-es/ducki-es.github.io/assets/70515562/74e61df3-af5c-4b60-a5bb-f368185d10ce)
![Image12](https://github.com/ducki-es/ducki-es.github.io/assets/70515562/1f734314-f5b8-4a62-8e8b-a3f5aa5c8e3b)
![Image13](https://github.com/ducki-es/ducki-es.github.io/assets/70515562/d62b422c-2ec5-4f55-b3cf-4a48f85e1868)
![Image14](https://github.com/ducki-es/ducki-es.github.io/assets/70515562/377e635a-70b8-4231-a571-0f4c9017931b)
![Image15](https://github.com/ducki-es/ducki-es.github.io/assets/70515562/3de95084-c396-4d83-8f64-86713f94ed44)
![Image16](https://github.com/ducki-es/ducki-es.github.io/assets/70515562/5164fdf2-390c-46b8-b3ea-1e8d059dc650)
![Image17](https://github.com/ducki-es/ducki-es.github.io/assets/70515562/14956d01-3efa-4b5d-8291-08125c96c8b3)
![Image18](https://github.com/ducki-es/ducki-es.github.io/assets/70515562/9c674add-8497-4fef-a327-9b4929af77ee)

**Comment by ZeroDayDaemon** [comment]
I need a public domain image

**Comment by MaloTV** [comment]
what you want from me
